name: C/C++ CI

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: apt
      run: sudo apt update && sudo apt install bison flex ninja-build lua5.3
    - name: make
      run: make

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: brew
      run: brew install ninja lua@5.4
    - name: make
      run: |
        make

  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        msystem: MINGW32
        install: >-
          make
          mingw-w64-i686-gcc
          mingw-w64-i686-lua
          mingw-w64-i686-nsis
          ninja
          bison
          flex
          zip
          git
    - uses: actions/checkout@v3
    - name: build
      run: |
        make LDFLAGS="-s -static" CFLAGS=-Os
    - name: package
      run: |
        make ack-setup.exe
    - name: upload setup
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.event.repository.name }}.${{ github.sha }}
        path: ack-setup.exe
